const nome = prompt("Qual o seu nome completo?")
const dataDeNascimento = prompt("Qual sua data de nascimento? Utilize as /")
const endereço = prompt("Qual o seu endereço?")
const cpf = Number (prompt("Qual o seu cpf?"))
const escolaridade = prompt("Qual a sua escolaridade?")
const cnh = confirm("Você possui cnh?")
const filhos = Number (prompt("Quantos filhos possui?"))
const cargoAtual = prompt("Qual o seu cargo atual?")
const salario = Number (prompt("Qual o seu salário?"))
const comissao = Number (prompt("Você recebe comissão? Se sim, informe a porcentagem, caso não, responda com zero"))
const admissao = Number (prompt("Qual o ano da sua admissão?"))

console.log(typeof nome)
console.log(typeof dataDeNascimento)
console.log(typeof endereço)
console.log(typeof cpf)
console.log(typeof escolaridade)
console.log(typeof cnh)
console.log(typeof filhos)
console.log(typeof cargoAtual)
console.log(typeof salario)
console.log(typeof comissao)
console.log(typeof admissao)

console.log("Relatório da pessoa colaboradora:")

console.log(nome)
console.log(dataDeNascimento)
console.log(endereço)
console.log(cpf)
console.log(escolaridade)
console.log(cnh)
console.log(filhos)
console.log(cargoAtual)
console.log(salario)
console.log(comissao)
console.log(admissao)